// src/app/dashboard/stocks/history/HistoryPdfGenerator.tsx

"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { RestockHistory, getRestockItemProduct } from "@/types/stocks.types";

interface HistoryPdfGeneratorProps {
  history: RestockHistory | RestockHistory[];
  isSingle: boolean;
  fileName?: string;
}

export default function HistoryPdfGenerator({
  history,
  isSingle,
  fileName = "ALL_STOCK_RECORDS.pdf",
}: HistoryPdfGeneratorProps) {
  const formatDateTime = (dateStr: string) => {
    const d = new Date(dateStr);
    const day = String(d.getDate()).padStart(2, "0");
    const month = String(d.getMonth() + 1).padStart(2, "0");
    const year = d.getFullYear();
    const hours = String(d.getHours()).padStart(2, "0");
    const minutes = String(d.getMinutes()).padStart(2, "0");
    return `${day}/${month}/${year} ${hours}:${minutes}`;
  };

  const generatePdf = () => {
    const doc = new jsPDF("p", "pt", "a4");

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const marginX = 40;
    let pageNo = 1;

    const footer = () => {
      doc.setFontSize(9);
      doc.setTextColor(100);
      doc.text(`Page ${pageNo}`, pageWidth / 2, pageHeight - 20, {
        align: "center",
      });
      doc.text(
        "Generated by IceCream Inventory System",
        pageWidth / 2,
        pageHeight - 8,
        { align: "center" }
      );
      pageNo++;
    };

    /* ================= HEADER ================= */
    doc.setFillColor(22, 163, 74);
    doc.rect(0, 0, pageWidth, 70, "F");

    doc.setTextColor(255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text(
      isSingle ? "RESTOCK HISTORY REPORT" : "ALL RESTOCK HISTORY",
      marginX,
      42
    );

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("IceCream Inventory System", marginX, 60);

    doc.setTextColor(0);

    /* ================= SINGLE RECORD ================= */
    if (isSingle) {
      const h = history as RestockHistory;
      const dateTime = formatDateTime(h.createdAt);
      const reason = h.items[0]?.note || "Restocking";

      doc.setFontSize(11);
      doc.text(`Date & Time : ${dateTime}`, marginX, 95);
      doc.text(`Reason     : ${reason}`, marginX, 112);
      doc.text(`Items Count: ${h.items.length}`, marginX, 129);

      const tableData = h.items.map((item, i) => {
        const product = getRestockItemProduct(item);
        return [
          i + 1,
          product.name,
          product.category || "-",
          `${item.quantity} ${product.unit}`,
        ];
      });

      autoTable(doc, {
        startY: 155,
        theme: "grid",
        head: [["#", "Product Name", "Category", "Quantity"]],
        body: tableData,
        styles: {
          fontSize: 10,
          cellPadding: 6,
          valign: "middle",
          lineWidth: 0.6,
          lineColor: [120, 120, 120],
          textColor: 20,
        },
        headStyles: {
          fillColor: [22, 163, 74],
          textColor: 255,
          fontStyle: "bold",
          halign: "center",
          lineWidth: 0.8,
          lineColor: [0, 0, 0],
        },
        columnStyles: {
          0: { cellWidth: 30, halign: "center" },
          1: { cellWidth: 200 },
          2: { cellWidth: 140 },
          3: { cellWidth: 120, halign: "center" },
        },
        alternateRowStyles: {
          fillColor: [245, 247, 250],
        },
        didDrawPage: footer,
      });

      doc.save(`RESTOCK-${dateTime.replace(/[/: ]/g, "-")}.pdf`);
      return;
    }

    /* ================= ALL RECORDS ================= */
    const histories = history as RestockHistory[];
    let y = 95;

    histories.forEach((h, index) => {
      if (y > pageHeight - 220) {
        doc.addPage();
        footer();
        y = 40;
      }

      const dateTime = formatDateTime(h.createdAt);
      const reason = h.items[0]?.note || "Restocking";

      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.text(`Record ${index + 1}`, marginX, y);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(`Date & Time : ${dateTime}`, marginX, y + 16);
      doc.text(`Reason     : ${reason}`, marginX, y + 30);
      doc.text(`Items Count: ${h.items.length}`, marginX, y + 44);

      const tableData = h.items.map((item, i) => {
        const product = getRestockItemProduct(item);
        return [
          i + 1,
          product.name,
          product.category || "-",
          `${item.quantity} ${product.unit}`,
        ];
      });

      autoTable(doc, {
        startY: y + 60,
        theme: "grid",
        head: [["#", "Product Name", "Category", "Quantity"]],
        body: tableData,
        styles: {
          fontSize: 9,
          cellPadding: 5,
          lineWidth: 0.5,
          lineColor: [120, 120, 120],
          textColor: 20,
        },
        headStyles: {
          fillColor: [22, 163, 74],
          textColor: 255,
          fontStyle: "bold",
          lineWidth: 0.8,
          lineColor: [0, 0, 0],
        },
        columnStyles: {
          0: { cellWidth: 30, halign: "center" },
          1: { cellWidth: 200 },
          2: { cellWidth: 140 },
          3: { cellWidth: 120, halign: "center" },
        },
        alternateRowStyles: {
          fillColor: [245, 247, 250],
        },
        didDrawPage: footer,
      });

      y = (doc as any).lastAutoTable.finalY + 30;
    });

    doc.save(fileName);
  };

  return (
    <button
      onClick={generatePdf}
      className="flex items-center gap-2 px-4 py-2 rounded-lg bg-green-600 hover:bg-green-700 text-white font-semibold shadow"
    >
      {isSingle ? "Download History" : "Download All Records"}
    </button>
  );
}
