// src/app/dashboard/stocks/history/HistoryPdfGenerator.tsx
"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { RestockHistory, getRestockItemProduct } from "@/types/stocks.types";

interface HistoryPdfGeneratorProps {
  history: RestockHistory | RestockHistory[];
  isSingle: boolean;
  fileName?: string;
}

export default function HistoryPdfGenerator({
  history,
  isSingle,
  fileName = "ALL_STOCK_RECORDS.pdf",
}: HistoryPdfGeneratorProps) {
  const formatDateTime = (dateStr: string) => {
    const d = new Date(dateStr);
    const day    = String(d.getDate()).padStart(2, "0");
    const month  = String(d.getMonth() + 1).padStart(2, "0");
    const year   = d.getFullYear();
    const hours  = String(d.getHours()).padStart(2, "0");
    const minutes = String(d.getMinutes()).padStart(2, "0");
    return `${day}/${month}/${year} ${hours}:${minutes}`;
  };

  // ─── Draw footers on ALL pages after content is finalized ───────────────────
  const drawAllFooters = (doc: jsPDF) => {
    const pageWidth  = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const totalPages = (doc as any).internal.getNumberOfPages();

    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(9);
      doc.setTextColor(100);
      doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 20, { align: "center" });
      doc.text("Generated by Ice Saathi - Ice Saathi Management System", pageWidth / 2, pageHeight - 8, { align: "center" });
    }
  };

  // ─── Shared table column styles ──────────────────────────────────────────────
  const colStyles = {
    0: { cellWidth: 35, halign: "center"  as const },
    1: { cellWidth: 195 },
    2: { cellWidth: 145 },
    3: { cellWidth: 130, halign: "center" as const },
  };

  const generatePdf = () => {
    const doc        = new jsPDF("p", "pt", "a4");
    const pageWidth  = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const marginX    = 40;

    // ── HEADER BANNER (drawn once on page 1) ──────────────────────────────────
    doc.setFillColor(22, 163, 74);
    doc.rect(0, 0, pageWidth, 70, "F");

    doc.setTextColor(255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text(isSingle ? "RESTOCK HISTORY REPORT" : "ALL RESTOCK HISTORY", marginX, 42);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Ice Saarthi", marginX, 60);
    doc.setTextColor(0);

    // ════════════════════════════════════════════════════════════════════════════
    // SINGLE RECORD
    // ════════════════════════════════════════════════════════════════════════════
    if (isSingle) {
      const h        = history as RestockHistory;
      const dateTime = formatDateTime(h.createdAt);
      const reason   = h.items[0]?.note || "Restocking";

      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(0);
      doc.text(`Date & Time : ${dateTime}`,    marginX, 95);
      doc.text(`Reason      : ${reason}`,      marginX, 112);
      doc.text(`Items Count : ${h.items.length}`, marginX, 129);

      const tableData = h.items.map((item, i) => {
        const product = getRestockItemProduct(item);
        return [
          i + 1,
          product.name,
          product.category || "-",
          `${item.quantity} ${product.unit || ""}`.trim(),
        ];
      });

      autoTable(doc, {
        startY: 155,
        theme: "grid",
        head: [["#", "Product Name", "Category", "Quantity"]],
        body: tableData,
        styles: {
          fontSize: 10,
          cellPadding: 6,
          valign: "middle",
          lineWidth: 0.6,
          lineColor: [120, 120, 120],
          textColor: 20,
        },
        headStyles: {
          fillColor:  [22, 163, 74],
          textColor:  255,
          fontStyle:  "bold",
          halign:     "center",
          lineWidth:  0.8,
          lineColor:  [0, 0, 0],
        },
        columnStyles: colStyles,
        alternateRowStyles: { fillColor: [245, 247, 250] },
        // ⚠ No didDrawPage here — footers are drawn in a single pass at the end
      });

      drawAllFooters(doc);
      doc.save(`RESTOCK-${dateTime.replace(/[/: ]/g, "-")}.pdf`);
      return;
    }

    // ════════════════════════════════════════════════════════════════════════════
    // ALL RECORDS
    // ════════════════════════════════════════════════════════════════════════════
    const histories = history as RestockHistory[];

    /**
     * y  — current vertical cursor on the CURRENT page.
     *       After autoTable we update it from lastAutoTable.finalY so it always
     *       reflects the actual end position of the last drawn element.
     */
    let y = 95; // start below the header on page 1

    histories.forEach((h, index) => {
      const dateTime = formatDateTime(h.createdAt);
      const reason   = h.items[0]?.note || "Restocking";

      // ── Info block height: 3 text lines (16px each) + gap before table ──
      const INFO_BLOCK_H = 16 * 3 + 12; // ≈ 60pt
      const EST_TABLE_H  = Math.min(h.items.length * 24, 200); // rough estimate

      // If info block + minimum table header won't fit, start a new page
      if (y + INFO_BLOCK_H + 40 > pageHeight - 40) {
        doc.addPage();
        y = 40;
      }

      // ── Record heading ────────────────────────────────────────────────────
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(0);
      doc.text(`Record ${index + 1}`, marginX, y);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(`Date & Time : ${dateTime}`,       marginX, y + 18);
      doc.text(`Reason      : ${reason}`,         marginX, y + 34);
      doc.text(`Items Count : ${h.items.length}`, marginX, y + 50);

      const tableData = h.items.map((item, i) => {
        const product = getRestockItemProduct(item);
        return [
          i + 1,
          product.name,
          product.category || "-",
          `${item.quantity} ${product.unit || ""}`.trim(),
        ];
      });

      autoTable(doc, {
        startY: y + INFO_BLOCK_H,
        theme: "grid",
        head: [["#", "Product Name", "Category", "Quantity"]],
        body: tableData,
        styles: {
          fontSize: 9,
          cellPadding: 5,
          lineWidth: 0.5,
          lineColor: [120, 120, 120],
          textColor: 20,
        },
        headStyles: {
          fillColor: [22, 163, 74],
          textColor: 255,
          fontStyle: "bold",
          lineWidth: 0.8,
          lineColor: [0, 0, 0],
        },
        columnStyles: colStyles,
        alternateRowStyles: { fillColor: [245, 247, 250] },
        // ⚠ No didDrawPage — footers are added at the very end
        showHead: "everyPage",
        rowPageBreak: "avoid",
      });

      // Advance y to just after the table (on whatever page it ended)
      y = (doc as any).lastAutoTable.finalY + 30;

      // ── Visual separator between records ──────────────────────────────────
      const sepPageH = (doc as any).internal.getCurrentPageInfo().pageNumber;
      const curPage  = (doc as any).internal.getNumberOfPages();

      // Only draw separator when we're still on the last page of the table
      // and there is a next record
      if (index < histories.length - 1) {
        const lineY = y - 15;
        if (lineY < pageHeight - 20) {
          doc.setDrawColor(200, 200, 200);
          doc.setLineWidth(0.5);
          doc.line(marginX, lineY, pageWidth - marginX, lineY);
        }
      }
    });

    // ── Draw page numbers on ALL pages now that the doc is complete ──────────
    drawAllFooters(doc);

    doc.save(fileName);
  };

  return (
    <button
      onClick={generatePdf}
      className="flex items-center gap-2 px-4 py-2 rounded-lg bg-green-600 hover:bg-green-700 text-white font-semibold shadow"
    >
      {isSingle ? "Download History" : "Download All Records"}
    </button>
  );
}