// src/app/dashboard/stocks/restock/RestockPdfGenerator.tsx


"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { RestockItem , getRestockItemProduct} from "@/types/stocks.types";

interface RestockPdfGeneratorProps {
  items: RestockItem[];
  dateTime: string;
  note: string;
  fileName: string;
}

export default function RestockPdfGenerator({
  items,
  dateTime,
  note,
  fileName,
}: RestockPdfGeneratorProps) {
  const generatePdf = () => {
    if (!items || items.length === 0) {
      alert("No restock items to export");
      return;
    }

    const doc = new jsPDF("p", "pt", "a4");

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const marginX = 40;

    /* ================= HEADER ================= */
    doc.setFillColor(22, 163, 74); // green-600
    doc.rect(0, 0, pageWidth, 70, "F");

    doc.setTextColor(255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("RESTOCK REPORT", marginX, 42);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Ice Saathi", marginX, 60);

    /* ================= META ================= */
    doc.setTextColor(0);
    doc.setFontSize(10);

    doc.text(`Generated On : ${dateTime}`, marginX, 95);
    doc.text(`Total Products Restocked : ${items.length}`, marginX, 110);

    /* ================= NOTE ================= */
    doc.setFont("helvetica", "bold");
    doc.text("Restock Note", marginX, 140);

    doc.setFont("helvetica", "normal");
    doc.text(note || "-", marginX, 155, {
      maxWidth: pageWidth - marginX * 2,
    });

    /* ================= SUMMARY ================= */
    const totalQuantity = items.reduce(
      (sum, item) => sum + Number(item.quantity || 0),
      0
    );

    doc.setFont("helvetica", "bold");
    doc.text("Summary", marginX, 185);

    doc.setFont("helvetica", "normal");
    doc.text(`• Total Items   : ${items.length}`, marginX, 205);
    doc.text(`• Total Quantity: ${totalQuantity}`, marginX, 220);

    /* ================= TABLE ================= */
   // ✅ AFTER
const tableBody = items.map((item, index) => {
  const product = getRestockItemProduct(item);
  return [
    index + 1,
    product.name,
    product.category || "-",
    `${item.quantity}`,
    product.unit,
    item.note || "-",
  ];
});

    autoTable(doc, {
      startY: 250,
      head: [
        ["#", "Product Name", "Category", "Quantity", "Unit", "Note"],
      ],
      body: tableBody,

      styles: {
        fontSize: 9,
        cellPadding: 6,
        textColor: 20,
        lineColor: [180, 180, 180],
        lineWidth: 0.5,
        valign: "middle",
      },

      headStyles: {
        fillColor: [22, 163, 74],
        textColor: 255,
        fontStyle: "bold",
        halign: "center",
        lineWidth: 0.5,
        lineColor: [22, 163, 74],
      },

      bodyStyles: {
        halign: "center",
      },

      columnStyles: {
        0: { cellWidth: 30, halign: "center" },
        1: { cellWidth: 130, halign: "left" },
        2: { cellWidth: 90, halign: "left" },
        3: { cellWidth: 70 },
        4: { cellWidth: 60 },
        5: { cellWidth: 120, halign: "left" },
      },

      alternateRowStyles: {
        fillColor: [245, 247, 250],
      },

      didDrawPage: (data) => {
        doc.setFontSize(9);
        doc.setTextColor(120);
        doc.text(
          `Page ${data.pageNumber}`,
          pageWidth / 2,
          pageHeight - 20,
          { align: "center" }
        );
      },
    });

    /* ================= FOOTER ================= */
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(
      "Generated by Ice Saathi",
      pageWidth / 2,
      pageHeight - 8,
      { align: "center" }
    );

    doc.save(fileName);
  };

  return (
    <button
      onClick={generatePdf}
      className="
        bg-blue-600 hover:bg-blue-700
        text-white
        px-5 py-2
        rounded-lg
        font-semibold
        shadow
      "
    >
      Download Restock Report
    </button>
  );
}

